### ISSUE TITLE
Leave old value instead of Unavailable

### ISSUE THREAD

**Issue by wes1993** [robbinjanssen/home-assistant-omnik-inverter#81] opened 2021-11-17 14:11 UTC
Hello,
We have some problem with this inverter that goes in unavailable state very often, instead of go in unavailble also in HA sensors could we leave the latest value readed? 
Se we don't have all this sensors unavailable also in HA, a little explanation:
If inverter not reply:
solar_current_power = 0
solar_energy_today = last value before connection lost
solar_energy_total =  last value before connection lost
Best Regards
Stefano

**Comment by robbinjanssen** [comment] 2021-11-18 10:36
@wes1993 therefor we will need some sort of caching layer, there already is an issue for this. Closing this issue :)

Duplicate of https://github.com/robbinjanssen/home-assistant-omnik-inverter/issues/51

**Closed by robbinjanssen** 2021-11-18 10:36 UTC

**Comment by wes1993** [comment] 2021-11-19 08:27
Sorry @robbinjanssen 
Thanks a lot and i hope you could find a way to add this feature

Bye
Stefano
