### ISSUE TITLE
A username/password is missing error after update to 2.4.0

### ISSUE THREAD

**Issue by mvdwetering** [robbinjanssen/home-assistant-omnik-inverter#113] opened 2022-06-04 09:50 UTC
## Detailed description

After updating from 2.3.0 to 2.4.0 the integration does not load anymore. It shows the following error in HA.

>Config entry 'Solis Omvormer' for omnik_inverter integration not ready yet: A username and/or password is missing from the request; Retrying in background

This is with a Ginlog Solis Wifistick that used to work before the update.

There are a username and password in the config entry and they are still valid (checked with a browser)

```
            {
                "entry_id": "30c76ef9eb2272bbf72832b70d4c700f",
                "version": 2,
                "domain": "omnik_inverter",
                "title": "Solis Omvormer",
                "data": {
                    "host": "192.168.178.32",
                    "source_type": "html",
                    "username": "**username**",
                    "password": "**password**"
                },
                "options": {},
                "pref_disable_new_entities": false,
                "pref_disable_polling": false,
                "source": "user",
                "unique_id": null,
                "disabled_by": null
            },
```

I did a quick scan through the changes, but nothing obvious popped out.

## Context

Not sure what to write here.

## Diagnostics

I don't see the diagnostics option for this integration?

**Comment by MarijnS95** [comment] 2022-06-04 09:50
This seems to be a:

Duplicate of #112

**Closed** 2022-06-04 10:07 UTC

**Comment by mvdwetering** [comment] 2022-06-04 15:18
Thanks for the quick fix, works great 👍

**Comment by MarijnS95** [comment] 2022-06-04 16:08
My apologies for breaking it in the first place, that was a poor 2-letter typo!
